server:
  port: 56085
  servlet:
    context-path: /sailing

spring:
  application:
    name: sailing

  main:
    allow-bean-definition-overriding: true



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379
    shutdown-timeout: 100
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 10000
    timeout: 10000
    password:

sms:
  qcloud:
    appId: 1400656610
    appKey: adf7a1f5150e09294798482d26bd59af
    templateId: 1358062
    sign: 酷猿xt个人网站

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml



