server:
  port: 56010

spring:
  application:
    name: nacos-restful-provider #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #服务发现中心地址
        namespace: 5da0b340-4df1-4a85-a80f-859feaacda30
